import {  IBM_Plex_Sans_Arabic } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Main/Navbar";
import Foote from "./components/Main/Footer";


// FONT Arabic
const ibm = IBM_Plex_Sans_Arabic({
  weight: ["100","200","300","400","500","600","700"],
  variable: "--ibm-plex-arabic",
  style: ["normal"],
  subsets: ["latin"]
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${ibm.variable}`}
      >
        <Navbar />
        {children}
        <Foote />
      </body>
    </html>
  );
}

